export const cars = [
  {
    model: "DASHING",
    title: "Jetour DASHING",
    mainphoto:
      "https://jetour-atlantm.by/uploads/car-model-landing/3l/ml/3LMlFiFome_AUTO_AUTO.webp",
    subtitle: "компактный кроссовер SUV-C",
    price: "94 900",
    img: "https://jetour-atlantm.by/uploads/tmp/it/sg/iTsgEKaNR0.png",
    body: {
      color: {
        white: [
          "https://jetour-atlantm.by/uploads/car-model-landing/hv/2z/hv2ZKgnS8a_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/k4/dy/k4dY6M2aqz_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/lo/8y/lO8ynIzxrI_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/bl/pt/BLPTiRELlT_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/1j/fu/1JFuxu55B0_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/36/fy/36Fy67HQXa_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/co/o2/COo25xflhd_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/xq/au/xQAU5lza2O_AUTO_AUTO.webp",
        ],
        blue: [
          "https://jetour-atlantm.by/uploads/car-model-landing/na/yk/nAykiYrfVU_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/8g/z5/8gz5fOVWFl_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/kj/kq/KJkqeLZkTZ_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/gp/zj/GpzJQWxT3F_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/g7/p7/G7p7IjhkzS_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/av/6c/av6cVXQLar_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/c0/vg/C0VGqBtGLQ_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/84/8x/848X2ZkcBX_AUTO_AUTO.webp",
        ],
        gray: [
          "https://jetour-atlantm.by/uploads/car-model-landing/cs/gs/cSgsjRgonE_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/cs/gs/cSgsjRgonE_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/wx/iz/wXIz4me0n1_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/6h/ie/6HIeA4Xlod_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/rl/ac/rLaCYc2OWt_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/xa/pe/xaPeW3g8a9_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/u2/1k/U21kzONjrv_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/0m/e2/0mE2j04fdh_AUTO_AUTO.webp",
        ],
        black: [
          "https://jetour-atlantm.by/uploads/car-model-landing/u7/5v/U75VKocZBG_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/7m/b9/7mb9jpnBIw_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/7e/l5/7El5wIh6NQ_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/nf/1h/NF1H921Jox_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/2b/bb/2BbBmOHCwF_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/fo/0j/Fo0jbO3Esq_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/rf/jw/rfJWlYS3vm_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/j4/xf/J4XFPlkCqm_AUTO_AUTO.webp",
        ],
      },
    },
    interior: {
      color: {
        white: [
          "https://jetour-atlantm.by/uploads/car-model-landing/rn/3f/rn3F4KUTno_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/wl/sd/wlSD2INwVP_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/ps/zo/PszO8kuQGy_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/vl/vx/VLVX5L0mjq_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/td/hq/TDhqFMXdRN_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/mi/t7/mIT7bEMfJC_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/se/lv/SeLVSWjD9q_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/kj/j6/KJJ6654Skd_AUTO_AUTO.webp",
        ],
        red: [
          "https://jetour-atlantm.by/uploads/car-model-landing/cm/ij/cmIj0IwboR_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/i8/rc/i8rCflxbI8_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/2z/gd/2ZGDTXgF0C_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/hf/ye/HfYe2ircHB_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/hf/ye/HfYe2ircHB_AUTO_AUTO.webp",
        ],
      },
    },
    info: [
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/lb/3m/lB3MPBztS1_AUTO_AUTO.webp",
        value: "180 км/ч",
        desc: "макс. скорость",
      },
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/ek/ci/eKci0uZ3fN_AUTO_AUTO.webp",
        value: "57 л",
        desc: "бак",
      },
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/8s/xg/8SxGiD4ebE_AUTO_AUTO.webp",
        value: "8,4 л",
        desc: "комб. расход",
      },
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/s5/mc/S5Mc9sc78e.png",
        value: "4590 мм",
        desc: "длина",
      },
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/n5/gs/n5gs8KM3I9_AUTO_AUTO.webp",
        value: "190 л. с",
        desc: "мощность",
      },
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/f7/7t/f77tSxRuUW_AUTO_AUTO.webp",
        value: "5",
        desc: "полноценных мест",
      },
    ],
    about: {
      titlepage: "Космотехнологический кроссовер",
      descpage: `Jetour DASHING - кроссовер, созданный для тех, кто стремится превзойти свои ожидания и освоить новые горизонты. Новый кроссовер от Jetour представляет собой воплощение элегантности, мощи и утонченности, позволяющей ощутить истинное удовольствие от вождения на любой дороге, в любой ситуации. 
      <br/>
      <br/>
   
      Поистине космический во всем.`,
      img: "https://jetour-atlantm.by/uploads/car-model-landing/d4/vk/D4vKvRL3ZO_AUTO_AUTO.webp",
    },
    slider: [
      "https://jetour-atlantm.by/uploads/car-model-landing/kb/f9/KBF9srwzLe_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/aw/vp/awVPnHDefG_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/fa/po/FapoCawyW0_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/2t/p8/2TP8usJQvw_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/di/lx/DiLxSujIbh_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/8a/cn/8ACN3Ulc3P_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/ze/jd/zEJd3bwbKD_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/ze/iy/zEiy3QAKgm_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/6p/2p/6P2PPcdJWx_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/ff/vp/FfvpkxRXF5_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/h6/4v/h64VxFjtG1_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/bp/0b/Bp0BCwvZw4_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/1p/sm/1PSm2ivCbH_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/n0/ta/N0TaIgYg1G_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/xs/pk/XspKt9SUCR_AUTO_AUTO.webp",
    ],
    hang: [
      {
        title: "Космическая внешность завораживает",
        desc: `Jetour DASHING – автомобиль, который поражает своей элегантностью, мощью и инновационными решениями в дизайне. Он является воплощением стиля, уюта и современных технологий, предлагая своим владельцам непревзойденный комфорт и удовольствие от вождения.<br /><br />

 

    Внешность кроссовера Jetour DASHING поражает и завораживает своей смелостью, неординарностью и элегантностью. Достаточно один раз увидеть Jetour DASHING, и его внешний облик сразу запоминается уникальным и стильным дизайном, нашедшим воплощение в каждой детали его экстерьера.<br /><br />
    
     
    
    Jetour DASHING предназначен для тех, кто стремится быть в центре внимания и вести активный образ жизни, несмотря на все преграды и ограничения.`,
        img: "https://jetour-atlantm.by/uploads/car-model-landing/ob/6c/OB6cycF2dn_AUTO_AUTO.webp",
        options: [
          {
            title: "Двухуровневая каскадная LED оптика фар",
            desc: "Двухуровневая каскадная LED оптика фар головного света придает автомобилю узнаваемость и выразительность. Притягивающая взгляд безрамочная фальшрешетка радиатора добавляет к этому тонкую нотку элегантности, наделяя кроссовер Jetour DASHING особым шармом и привлекательностью.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/cy/i9/Cyi91WfNdS_AUTO_AUTO.webp",
          },
          {
            title: "Выдвижные дверные ручки",
            desc: "Выдвижные дверные ручки кроссовера гармонично сочетаются со стремительными формами кузова автомобиля. Их линии вторят линиям боковых стекол, подчеркивая спортивные нотки и динамику во внешности Jetour DASHING.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/oz/ju/oZjukyE1VA_AUTO_AUTO.webp",
          },
          {
            title: "19-дюймовые легкосплавные диски",
            desc: "19-дюймовые легкосплавные диски оригинального дизайна придают кроссоверу брутальный вид, добавляя характера всему внешнему облику автомобиля. Подчеркнутые пластиковыми вставками колесные арки делают внешность Jetour DASHING еще более решительной.  Отдельные формованные пластиком пороги и нижние части дверей, удачно гармонирующие с подштамповками на боковинах кузова, прекрасно дополняют динамичный и смелый облик автомобиля.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/jd/d9/jDd90rFx9z_AUTO_AUTO.webp",
          },
          {
            title: "Элегантный профиль кроссовера",
            desc: 'Задняя часть кузова кроссовера Jetour DASHING привлекает взор своими оригинальными дизайнерскими решениями ничуть не меньше. Острая "корма"  c диодной оптикой необычной формы органично вписывается в эффектный образ современного автомобиля для покупателей, которые желают выделиться из серой массы. Практичный и стильный диффузор в нижней части заднего бампера демонстрирует внимание дизайнеров не только к внешним эффектам, а и к функциональности автомобиля. Добавляя спортивные нотки внешности Jetour DASHING, он способствует оптимизации аэродинамики кроссовера и эффективному распределению потоков воздуха, выходящих из-под автомобиля. Дерзкий спойлер над задним стеклом также добавляет во внешний облик Jetour DASHING динамики и стремительности, внося свою лепту в его неординарный облик.',
            img: "https://jetour-atlantm.by/uploads/car-model-landing/fi/j3/FIJ37mgqIV_AUTO_AUTO.webp",
          },
          {
            title: "Компактные внешние габариты",
            desc: "Компактные внешние габариты Jetour DASHING (длина 4590 мм, ширина 1900 мм, высота 1685 мм) делают кроссовер очень удобным в повседневной эксплуатации.  Благодаря колесной базе в 2720 мм и водителю и пассажирам кроссовера предлагается достаточное количество места для комфортабельных поездок на любые расстояния.  Величина дорожного просвета Jetour DASHING – 160 мм. Подобный клиренс одинаково удачно подходит как для городской езды, так и для поездок по пересеченной местности.  Ширина передней колеи кроссовера составляет 1610 мм, задней – 1615 мм. В сочетании с колесной базой в 2720 мм такая геометрия расположения колес способствует высокой стабильности автомобиля на дороге и обеспечивает ему оптимальную устойчивость и управляемость..",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/8w/i2/8Wi2mwKWfY_AUTO_AUTO.webp",
          },
        ],
      },
      {
        title: "Высокая функциональность и элегантное исполнение",
        desc: `Интерьер кроссовера Jetour DASHING впечатляет своей элегантностью и высоким уровнем комфорта, предоставляя водителю и пассажирам отличные условия для приятных поездок.<br/><br/> 

 

        Передняя панель, ниспадающая волной к нижней части салона, придаёт интерьеру динамичный и современный вид. Вставки под дерево или карбон создают приятные контрасты в оформлении салона и добавляют интерьеру DASHING утонченности и элегантности.<br/><br/>
        
         
        
        Удобные и функциональные карты дверей обеспечивают легкий доступ к необходимым предметам, а двухспицевое рулевое колесо, обтянутое натуральной кожей, предоставляет водителю полный контроль над автомобилем.`,
        img: "https://jetour-atlantm.by/uploads/car-model-landing/hh/lm/HHlMkNSBMU_AUTO_AUTO.webp",
        options: [
          {
            title: "Панорамный люк",
            desc: "Площадь панорамного люка внедорожника DASHING – внушительные более 1 квадратных метра, а толщина теплоизоляционного стекла – 5 мм. Управлять сдвижной секцией можно с клавиши из салона. Предусмотрено автоматическое закрывание люка на случай дождя.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/zj/ul/zJuLjeX0Q5_AUTO_AUTO.webp",
          },
          {
            title: "Амбиентная подсветка",
            desc: "Амбиентная подсветка создает уютную и расслабляющую атмосферу в салоне автомобиля, дополняя общую эстетику его интерьера. Она позволяет создать разные настроения в зависимости от предпочтений водителя и пассажиров.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/dg/t7/Dgt7numppT_AUTO_AUTO.webp",
          },
          {
            title: "Вместительный салон",
            desc: "Несмотря на внушительные габариты, флагманский кроссовер получился очень стремительным, утонченным и «чистым». В этом заслуга большой площади остекления, изящного спойлера на пятой двери, интегрированных в боковые зеркала указателей поворота и множества других элементов.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/7a/oe/7aoEK3nz3L_AUTO_AUTO.webp",
          },
          {
            title: "Анатомические сиденья",
            desc: "Анатомические сиденья водителя и переднего пассажира с интегрированными в них подголовниками гарантируют оптимальную поддержку и комфорт в Jetour DASHING во время поездок на любые расстояния. Удобные подлокотники спереди и сзади позволяют расслабиться и насладиться поездкой. Сиденья с электрорегулировками, подогревом и вентиляцией обеспечивают идеальную посадку и комфорт в любое время года.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/cv/i7/Cvi7Q7vl4k_AUTO_AUTO.webp",
          },
          {
            title: "Места для хранения",
            desc: "Много мест для хранения вещей и удобный подлокотник на втором ряду сидений позволяют организовать пространство так, как вам нужно для конкретных целей или мероприятий.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/cj/5q/CJ5Q4pP9PU_AUTO_AUTO.webp",
          },
          {
            title: "Трансформация салона",
            desc: "Широкие возможности трансформации и огромный багажник позволяют подготовить салонное пространство для решения любых задач.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/yy/lu/yYLUNvzhPy_AUTO_AUTO.webp",
          },
          {
            title: "Функциональный багажник",
            desc: "Объем багажника DASHING в пятиместной конфигурации составляет 420 литров. А максимальная глубина при сложенном втором ряде сидений превышает 2 метра: перевозка длинномеров не станет проблемой. Сервопривод багажной двери с возможностью управления с ключа поможет сохранить руки чистыми. Угол открывания пятой двери можно настроить.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/xk/bo/xkBOBHj6Q4_AUTO_AUTO.webp",
          },
          {
            title: "Усиленная шумоизоляция",
            desc: "Усиленная шумоизоляция отсека двигателя, лобовое стекло и стекла передних дверей с шумоподавлением создают уютное тихое пространство. Уровень шума на холостом ходу в салоне автомобиля составляет всего 38,5 дБ.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/r0/vj/r0VjKD6wjO_AUTO_AUTO.webp",
          },
        ],
      },
      {
        title: "Jetour DASHING – ваш персональный космический шаттл",
        desc: `Добро пожаловать в «Центр управления полетом». Качество, удобство, смарт-технологии в передовом оснащении салона.`,
        img: "https://jetour-atlantm.by/uploads/car-model-landing/pe/q8/pEq8AsXHiI_AUTO_AUTO.webp",
        options: [
          {
            title: "Цифровой мультимедийный кокпит",
            desc: "Цифровой кокпит кроссовера DASHING включает кластер из двух дисплеев высокого разрешения. Мощный процессор обеспечивает быстроту отклика мультимедийного экрана на уровне самых передовых гаджетов. Электронный щиток приборов с диагональю 8 дюймов предоставляет ясную и наглядную информацию о состоянии автомобиля, скорости, расходе топлива и других важных параметрах. Огромный цветной сенсорный экран (15,6”) в центральной части приборной панели является центром управления и информации автомобиля, предоставляя доступ к различным функциям, включая мультимедийную систему, навигацию и другие возможности.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/ve/db/VedBRaCC1n_AUTO_AUTO.webp",
          },
          {
            title:
              "Сенсорный дисплей в центре приборной панели - 12.8” или 15.6”",
            desc: "Большой сенсорный дисплей в центре приборной панели - 12.8” или 15.6” в зависимости от комплектации.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/i7/me/I7MeDsFkGk_AUTO_AUTO.webp",
          },
          {
            title: "Премиальная аудиосистема SONY",
            desc: "Премиальная акустика Sony придает объем звучанию музыки благодаря 8-ми динамикам, а возможности аудиосистемы позволяют максимально персонализировать настройки. Также присутствует возможность компенсации громкости при наборе скорости.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/rv/4w/Rv4W5jk0cz_AUTO_AUTO.webp",
          },
          {
            title: "Дополнительные динамики в подголовниках",
            desc: "Премиальная аудиосистема с динамиками даже в подголовниках передних сидений создает окружающую звуковую среду и позволяет наслаждаться качественным звуком во время движения автомобиля.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/bq/b9/BqB9uAkK0e_AUTO_AUTO.webp",
          },
          {
            title: "Беспроводная зарядка",
            desc: "Беспроводная зарядка для устройств на центральном тоннеле, практичные подстаканники и USB-порты для зарядки электронных гаджетов обеспечивают удобство и свободу в использовании современных технологий в пути.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/eg/eh/EGeHWzK5Fw_AUTO_AUTO.webp",
          },
          {
            title: "Продвинутая система очистки воздуха",
            desc: "Система очистки воздуха оснащена датчиком твердых частиц класса РМ2.5 (частицы менее 2,5 мкм), воздушным фильтром стандарта CN95, обеспечивающим фильтрацию воздуха на 95%, и генераторо отрицательных ионов, что позволяет наслаждаться чистым воздухом в салоне",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/kv/5j/kv5jOBSTZj_AUTO_AUTO.webp",
          },
          {
            title: "Пакет зимних опций",
            desc: "Зимний пакет, теперь также доступный в Jetour DASHING, включает в себя дополнительные опции для обеспечения комфорта и безопасности в холодное время года.  Обогрев ветрового стекла (Heated Windshield) помогает быстро размораживать и очищать стекло ото льда, снега и инея после длительной стоянки. Он также предотвращает образование запотевания на стеклах, обеспечивая водителю хороший обзор. Обогрев руля (Heated Steering Wheel) повышает комфорт от управления Jetour X1 при низких температурах. При включении этой функции обод рулевого колеса нагревается, что помогает избежать ощущения холода и сохранить удобство управления автомобилем. Обогрев сидений (Heated Seats) обеспечивает комфорт и уют для водителя и пассажиров, быстро согревая сиденья в холодные дни. Обогрев форсунок стеклоомывателей (Heated Washer Nozzles) предотвращает их замерзание и обледенение при температурах ниже нуля.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/ig/qg/iGQG9s2KGg_AUTO_AUTO.webp",
          },
        ],
      },
      {
        title: "Cосредоточен на вашей безопасности",
        desc: `Когда дело касается безопасности, кроссовер Jetour DASHING занимает лидирующую позицию. Снабженный передовыми технологиями и инновационными функциями этот автомобиль обеспечивает защиту вас и ваших пассажиров на каждом этапе поездки.<br/><br/>

 

        Оснащенный фронтальными и боковыми подушками безопасности, боковыми шторками безопасности, системой крепления детских кресел ISOFIX, автоматической блокировкой дверей в движении, датчиком столкновения и антиблокировочной системой тормозов Jetour DASHING предлагает всестороннюю защиту в случае возможных аварийных ситуаций.<br/><br/>
        
         
        
        Управляя Jetour DASHING, вы можете наслаждаться комфортным и уверенным вождением, зная, что вас и ваших пассажиров всегда окружает надежная система безопасности.<br/><br/>
        
         
        
        Наивысшая оценка C-NCAP.`,
        img: "https://jetour-atlantm.by/uploads/car-model-landing/a6/hs/a6HsgHfXwf_AUTO_AUTO.webp",
        options: [
          {
            title: "Инновационные подушки безопастности",
            desc: "Фронтальные подушки безопасности для водителя и переднего пассажира гарантируют им надежную защиту при фронтальном столкновении. Боковые подушки безопасности передних сидений дополнительно обеспечивают защиту в случае бокового столкновения либо удара в препятствие под углом, снижая риск получения серьезных повреждений. Jetour DASHING также оснащен боковыми шторками безопасности, задача которых предотвратить травмы у водителя и пассажиров при боковом ударе, создавая дополнительный барьер между людьми и потенциальной опасностью.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/hq/p3/hqP3Px7y9C_AUTO_AUTO.webp",
          },
          {
            title: "Высокопрочная сталь кузова",
            desc: "Доля высокопрочной стали в каркасе кузова составляет 70%. Предел прочности используемой стали достигает 1500 МПа. 54% панелей кузова имеет двухстороннюю оцинковку.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/26/yt/26ytWBIYdz_AUTO_AUTO.webp",
          },
          {
            title: "Системы крепления детских кресел",
            desc: "Заботясь о юных пассажирах, для перевозки которых используются детские сиденья, Jetour DASHING предлагает систему крепления детских кресел ISOFIX. С этой системой установка детского кресла становится легкой и надежной, при этом обеспечивается высокий уровень безопасности и комфорта для самых маленьких пассажиров кроссовера.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/bw/9v/BW9v2QvlNk_AUTO_AUTO.webp",
          },
          {
            title: "Автоматическая блокировка дверей",
            desc: "Автоматическая блокировка дверей в движении обеспечивает дополнительную безопасность, предотвращая случайное открытие дверей в процессе езды. Это гарантирует, что все двери останутся надежно закрытыми до тех пор, пока автомобиль не остановится полностью. В случае аварии в Jetour DASHING срабатывает датчик столкновения, который мгновенно разблокирует двери, обеспечивая быстрый и безопасный выход для вас и ваших пассажиров.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/qq/qg/qQQG7OZDC4.png",
          },
          {
            title: "Антиблокировочная система тормозов",
            desc: "Чтобы предотвратить блокировку колес и повысить управляемость, все Jetour DASHING по умолчанию оснащены антиблокировочной системой тормозов, которая позволяет безопасно и контролируемо снижать скорость и делать необходимые маневры на дороге.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/vm/5h/vM5HwMjyr4_AUTO_AUTO.webp",
          },
        ],
      },
      {
        title: "Интеллектуальные ассистенты",
        desc: `Jetour DASHING обладает обширным набором систем помощи водителю, предназначенных для обеспечения высокого уровня безопасности и комфорта в процессе управления кроссовером.`,
        img: "https://jetour-atlantm.by/uploads/car-model-landing/cw/h4/cwh4BK0AFI_AUTO_AUTO.webp",
        options: [
          {
            title: "Keyless Engine Start",
            desc: "Кроссовер обеспечивает бесключевой доступ в салон автомобиля с возможностью выбора количества разблокируемых дверей, и автоматически запирает двери и поднимает стекла при выходе человека с ключом из автомобиля.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/am/ii/amiIrCS07E_AUTO_AUTO.webp",
          },
          {
            title: "Система предупреждения о столкновении",
            desc: "Система предупреждения о столкновении (Forward Collision Warning) мониторит дорожную обстановку перед автомобилем. В случае обнаружения препятствия или возможности столкновения упомянутая система также предупреждает водителя звуковыми и визуальными сигналами, чтобы помочь избежать аварий.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/oo/0k/oo0kqoJpyB_AUTO_AUTO.webp",
          },
          {
            title: "Система автоматического включения ближнего света фар",
            desc: "Система автоматического включения ближнего света фар  обнаруживает другие транспортные средства на дороге и автоматически переключает свет фар между дальним и ближним режимами. Она помогает обеспечить наилучшую видимость для водителя и других участников движения, не ослепляя других водителей. Датчики света и дождя в автоматическом режиме включают ближний свет фар при снижении уровня освещения вокруг автомобиля и активизируют работу щеток стеклоочистителя ветрового стекла при появлении атмосферных осадков, ухудшающих видимость дороги.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/en/ae/enAEnyG6CI_AUTO_AUTO.webp",
          },
          {
            title: "Система предупреждения о выходе из полосы движения",
            desc: "Система предупреждения о выходе из полосы движения (Lane Departure Warning System) отслеживает полосу движения автомобиля и предупреждает о её смене, в случае, если она не обозначена водителем - включением сигнала поворота. Фиксируя дорожную разметку с помощью камеры штатного видеорегистратора автомобиля, LDWS определяет положение автомобиля относительно разделительных полос и в случае изменения траектории его движения оповещает об этом водителя, предотвращая случайные выезды на встречную полосу или на обочину.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/gk/bq/GkBQIQdU7o_AUTO_AUTO.webp",
          },
          {
            title:
              "Система помощи при парковке (Parking Assist + 360-Degree Camera System)",
            desc: "Система помощи при парковке (Parking Assist) использует датчики для автоматического обнаружения парковочного места и помогает водителю быстро и точно осуществить парковку. Она может предоставлять информацию о расстоянии до препятствий и давать указания водителю о направлении поворота руля для успешного и эффективного маневрирования задним ходом. Камеры кругового обзора (360-Degree Camera System), расположенные вокруг автомобиля, предоставляют водителю полный обзор пространства, окружающего кроссовер. Отображая полученные изображения на мультимедийном экране, они помогают водителю маневрировать в ограниченном пространстве и парковаться, избегая столкновений с окружающими препятствиями.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/e7/cb/E7Cbdrvslt_AUTO_AUTO.webp",
          },
          {
            title: "Система мониторинга слепых зон",
            desc: "Система мониторинга слепых зон  мониторит области, находящиеся вне прямого поля зрения водителя, и предупреждает о наличии транспортных средств в слепых зонах. В ходе своей работы она использует радары или камеры, расположенные на заднем бампере, и предупреждает водителя с помощью звуковых или визуальных сигналов.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/nl/vm/nlvMf6PoKl_AUTO_AUTO.webp",
          },
          {
            title: "Система контроля температуры и давления в шинах",
            desc: "Система контроля температуры и давления в шинах (Tire Pressure Monitoring System) мониторит давление воздуха и температуру в шинах автомобиля. Если давление становится ниже рекомендуемого уровня или возникают аномальные значения температуры, система предупреждает водителя о необходимости проверки и подкачки шин.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/yz/ri/yZRIR1bZtH_AUTO_AUTO.webp",
          },
          {
            title: "Интелектуальные системы торможения",
            desc: "Электронная система экстренного торможения (Emergency Brake Assist) в случае необходимости экстренного торможения и недостаточного при этом усилия на педали тормоза самостоятельно повышает давление в тормозной магистрали, делая это намного и эффективнее человека, управляющего автомобилем. Электронная система стабилизации (Electronic Stability Control) контролирует курсовую устойчивость автомобиля путем регулирования мощности и тормозных усилий на отдельных колесах. Она помогает предотвратить заносы автомобиля при резких маневрах или на скользком покрытии дороги. Противобуксовочная система (Traction Control System) предотвращает проскальзывание ведущих колес при разгоне на скользкой поверхности или на поверхности с разными коэффициентами сцепления колес с дорогой. Регулируя величину крутящего момента, она обеспечивает его оптимальное распределение между ведущими колесами автомобиля.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/j1/nq/J1nqMveo11_AUTO_AUTO.webp",
          },
        ],
      },
    ],
    delivery: {
      img: "https://jetour-atlantm.by/uploads/car-model-landing/z0/aq/Z0aQaomMJY_AUTO_AUTO.png",
      carsdelivery: [
        {
          title: "Галактический черный",
          img: "https://jetour-atlantm.by/uploads/car-model-landing/nn/ld/NNLdY3apTx.webp",
          complect: [
            "Dashing | Комл.: Luxury | Двигатель: 1.5T+6DCT | Кузов: Black | Интерьер: Black-red",
            "Dashing | Комл.: Luxury + | Двигатель: 1.6T+7DCT | Кузов: Black | Интерьер: Black-red",
            "Dashing | Комл.: Luxury + | Двигатель: 1.6T+7DCT | Кузов: Black | Интерьер: Gray-white",
          ],
        },
        {
          title: "Арктический белый",
          img: "https://jetour-atlantm.by/uploads/car-model-landing/c0/ix/c0IXoN67Af.webp",
          complect: [
            "Dashing | Компл.: Elite | Двигатель: 1.5T+6DCT | Кузов: White | Интерьер: Black-red",
            "Dashing | Компл.: Luxury + | Двигатель: 1.6T+7DCT | Кузов: White | Интерьер: Black-red",
            "Dashing | Компл.: Luxury + | Двигатель: 1.6T+7DCT | Кузов: White | Интерьер: Gray-white",
            "Dashing | Компл.: Luxury | Двигатель: 1.6T+7DCT | Кузов: White | Интерьер: Gray-white",
          ],
        },
        {
          title: "Океанический синий",
          img: "https://jetour-atlantm.by/uploads/car-model-landing/91/mv/91MvNVMbk4.webp",
          complect: [
            "Dashing | Компл.: Elite | Двигатель: 1.5T+6DCT | Кузов: Red | Интерьер: Black-red",
            "Dashing | Компл.: Luxury | Двигатель: 1.5T+6DCT | Кузов: Blue | Интерьер: Gray-white",
            "Dashing | Компл.: Luxury | Двигатель: 1.5T+6DCT | Кузов: Blue | Интерьер: Black-red",
            "Dashing | Компл.: Luxury + | Двигатель: 1.6T+7DCT | Кузов: Blue | Интерьер: Black-red",
            "Dashing | Компл.: Luxury + | Двигатель: 1.6T+7DCT | Кузов: Blue | Интерьер: Gray-white",
          ],
        },
        {
          title: "Призрачный серый",
          img: "https://jetour-atlantm.by/uploads/car-model-landing/ju/tr/jUtrNjogK8.webp",
          complect: [
            "Dashing | Компл.: Luxury | Двигатель: 1.5T+6DCT | Кузов: Gray | Интерьер: Gray-white",
            "Dashing | Компл.: Luxury + | Двигатель: 1.6T+7DCT | Кузов: Gray | Интерьер: Black-red",
            "Dashing | Компл.: Luxury + | Двигатель: 1.6T+7DCT | Кузов: Gray | Интерьер: Gray-white",
          ],
        },
        {
          title: "Страстный красный",
          img: "https://jetour-atlantm.by/uploads/car-model-landing/t8/rn/T8rnyZU2gl.webp",
          complect: [
            "Dashing | Компл.: Luxury | Двигатель: 1.5T+6DCT | Кузов: Red | Интерьер: Black-red",
            "Dashing | Компл.: Luxury | Двигатель: 1.5T+6DCT | Кузов: Red | Интерьер: Gray-white",
            "Dashing | Компл.: Luxury + | Двигатель: 1.6T+7DCT | Кузов: Red | Интерьер: Black-red",
            "Dashing | Компл.: Luxury + | Двигатель: 1.6T+7DCT | Кузов: Red | Интерьер: Gray-white",
          ],
        },
      ],
    },
    photoForm:
      "https://jetour-atlantm.by/uploads/car-model-landing/y6/k5/Y6k5zp6CYB_AUTO_AUTO.webp",
    complect: [
      {
        option: {
          dimensions: [
            "Длина, мм",
            "Ширина, мм",
            "Высота, мм",
            "Свес передний, мм",
            "Свес задний, мм",
            "Колея передних / задних колес, мм",
            "Угол заезда / съезда с препятствия",
            "Колесная база, мм",
            "Дорожный просвет, мм",
          ],
          capacity: [
            "Пространство для ног (спереди / сзади), мм",
            "Высота от сиденья до потолка, (спереди / сзади), мм",
            "Ширина салона на уровне плеч, (спереди / сзади), мм",
            "Ширина салона на уровне бедер, (спереди / сзади), мм",
            "Объем багажного отделения (VDA), л",
          ],
          engine: [
            "Двигатель",
            "Привод",
            "Тип коробки передач",
            "Экологический класс",
            "Количество цилиндров",
            "Количество клапанов",
            "Рабочий объем, см3",
            "Система питания (тип)",
            "Система зажигания (тип)",
            "Топливо",
            "Макс. мощность, кВт / Об.мин",
            "Макс. мощность, л.с. / Об.мин",
            "Макс. крутящий момент, Н·м / Об.мин",
            "Степень сжатия",
          ],
          weight: ["Снаряженная, max., кг", "Полная, кг"],
          dymanics: [
            "Максимальная скорость, км / ч",
            "Разгон: 0 → 100 км/ч, с",
          ],
          fueleconomy: [
            "Объем топливного бака, л",
            "Расход город, л / 100 км",
            "Расход трассал, л / 100 км",
            "Комбинированный, л / 100 км",
          ],
          brakes: ["Передние / Задние"],
          suspension: ["Передние / Задние"],
          warmoptions: [
            "Подогрев передних форсунок стеклоомывателя",
            "Подогрев лобового стекла",
            "Подогрев боковых зеркал",
            "Подогрев рулевого колеса",
            "Подогрев передних сидений",
            "Подогрев заднего ряда сидений",
            "Подогрев заднего стекла",
          ],
          security: [
            "Система Эра-Глонасс",
            "Подушки безопасности водителя и переднего пассажира",
            "Передние боковые подушки безопасности",
            "Шторки безопасности",
            "Антиблокировочная тормозная система (ABS)",
            "Система распределения тормозных усилий (EBD)",
            "Система помощи при торможении (BAS)",
            "Противобуксовочная система (TCS)",
            "Система курсовой устойчивости (ESC)",
            "Система помощи при старте в гору (HSA)",
            "Система помощи при спуске с горы (HDC)",
            "Система предотвращения опрокидывания (RMI)",
            "Иммобилайзер",
            "Центральный замок",
            "Система контроля давления в шинах (TPMS)",
            "Напоминание о непристегнутых передних ремнях безопасности",
            "Система удержания детских кресел Isofix для задних сидений",
          ],
          exterior: [
            "Панорамная крыша с электроприводом",
            "Скрытые дверные ручки",
            "Светодиодные фары",
            "Светодиодные дневные ходовые огни",
            "Повторители сигналов поворота в корпусах наружных зеркал",
            "Бескаркасные щетки стеклоочистителей",
            "Задняя бескаркасная щетка стеклоочистителя",
            "Заднее тонированное стекло",
            'Легкосплавные диски 19" с шинами 235 /55 R19',
            "Временное запасное колесо",
          ],
          comfort: [
            "Климат-контроль",
            "Двухзонный климат-контроль",
            "Салонный фильтр стандарта CN95",
            "Круиз-контроль",
            "Бесключевой доступ и запуск двигателя кнопкой",
            "Датчик дождя",
            "Датчик света",
            "Автоматическое запирание и поднятие окон при выходе из автомобиля",
            "Передние и задние стеклоподъемники с функцией автоматического закрытия и защитой от защемления",
            "Дистанционное управление закрытием окон с ключа",
            "Дистанционный запуск двигателя с ключа",
            "Напоминание о забытом ключе и забытом телефоне",
            "Боковые зеркала заднего вида с электрорегулировкой",
            "Электропривод складывания боковых зеркал заднего вида",
            "Автоматический наклон боковых зеркал при включении задней передачи",
            "Приветственная лазерная подсветка",
            "Передний парктроник",
            "Задний парктроник",
            "Электропривод двери багажника",
            "Умная очистка воздуха (воздушний фильтр PM 2.5)",
            "Ионизатор воздуха",
            "Мониторинг угарного газа",
          ],
          interior: [
            "Руль с кожаной отделкой",
            "Регулировка рулевой колонки по высоте и вылету",
            "Цифровая приборная панель",
            "Электронный рычаг переключения передач",
            "Подрулевой переключатель режимов КПП",
            "Кожаная отделка сидений",
            "Спортивное кресло водителя с электрической регулировкой в 6 направлениях",
            "Электропривод поясничного подпора сиденья водителя",
            "Спортивное кресло пассажира с электрической регулировкой в 4 направлениях",
            'Сиденье водителя с памятью, с функцией "welcome home" и памятью положения боковых зеркал',
            "Вентиляция передних сидений",
            "Очечник",
            "Передний центральный подлокотник с системой обогрева и охлаждения",
            "Центральный подлокотник 2-го ряда с подстаканниками",
            "Регулируемый угол наклона спинки 2-го ряда",
            "Атмосферная подсветка интерьера",
            "Передние накладки на пороги",
            "Передние накладки на пороги с подсветкой",
            "Задние накладки на пороги",
            "Шторка в багажник",
          ],
          mult: [
            "Центральный дисплей с экраном 12,8 дюйма",
            "Центральный дисплей с экраном 15,6 дюйма",
            "Интеллектуальное голосовое управление",
            "Беспроводная проекция экрана мобильного телефона (CarbitLink)",
            "Дисплей для отображения показателей окружающей среды",
            "Аудиосистема, количество динамиков, шт.",
            "Динамик в подголовнике",
            "Декоративная подсветка центрального динамика на центральной консоли",
            "Наружное музыкальное приветствие",
            "Беспроводная зарядка для телефона мощностью 40 Вт",
            "2 USB-разъема на переднем ряду (Type-C, быстрая зарядка)",
            "USB интерфейс под ящиком подлокотника (передача данных)",
            "USB-разъем на заднем ряду",
            "Коммуникационная система Bluetooth©",
            "Сигнализация превышения скорости 120 ± 5 км, с регулировкой",
            "Система помощи при парковке задним ходом с траекторией движения",
            "Функция обзора пространства под днищем автомобиля (180°)",
            "Система предупреждения столкновений сбоку при движении задним ходом (RCTA)",
            "Система мониторинга слепых зон (BSD)",
            "Предупреждение при открывании дверей (DOW)",
            "Система помощи при перестроении (LCW)",
            "Адаптивный круиз-контроль",
            "Система адаптивного переключения дальнего и ближнего света (HMA)",
            "Система предотвращения фронтальных столкновений (FCW)",
            "Система аварийного торможения (AEBS)",
            "Система предупреждения отклонения с дорожной полосы (LDWS)",
          ],
        },
      },
      {
        img: "https://jetour-atlantm.by/uploads/car-model-compare-landing/bg/7b/bG7BB6MqxO_AUTO_AUTO.webp",
        title: "Elite",
        price: "94 900",
        option: {
          dimensions: [
            "4590",
            "1900",
            "1685",
            "948",
            "922",
            "1610 / 1615",
            "19° / 22°",
            "2720",
            "160",
          ],
          capacity: [
            "1043 / 960",
            "915 / 896",
            "1470 / 1400",
            "1420 / 1420",
            "486 / 977",
          ],
          engine: [
            "Бензиновый 1,5TMPI",
            "2WD",
            "Коробка передач с двойным сцеплением мокрого типа (DCT)",
            "Евро 6",
            "4 цилиндра в ряд",
            "16 клапанов",
            "1498",
            "Распределенный впрыск топлива с электронным управлением",
            "Микропроцессорная",
            "Бензин с октановым числом не менее 92",
            "108 / 5500",
            "147 / 5500",
            "210 / (1750 - 4000)",
            "9,5:1",
          ],
          weight: ["1628", "1928"],
          dymanics: ["180", "11,8"],
          fueleconomy: ["57", "10,3", "6,5", "7,8"],
          brakes: ["Дисковые / Дисковые"],
          suspension: [
            "Независимая, типа Макферсон, пружинная, с телескопическими гидравлическими амортизаторами и стабилизатором поперечной устойчивости.",
            "Независимая, многорычажная, пружинная, с телескопическими гидравлическими амортизаторами и стабилизатором поперечной устойчивости.",
          ],
          warmoptions: [true, true, true, true, true, false, true],
          security: [
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
          ],
          exterior: [
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
          ],
          comfort: [
            false,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            false,
            false,
            false,
          ],
          interior: [
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            false,
            false,
            true,
            false,
            true,
            true,
          ],
          mult: [
            true,
            false,
            true,
            true,
            false,
            "4",
            false,
            false,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
        },
      },
      {
        img: "https://jetour-atlantm.by/uploads/car-model-compare-landing/bg/7b/bG7BB6MqxO_AUTO_AUTO.webp",
        title: "Luxury",
        price: "98 900",
        option: {
          dimensions: [
            "4590",
            "1900",
            "1685",
            "948",
            "922",
            "1610 / 1615",
            "19° / 22°",
            "2720",
            "160",
          ],
          capacity: [
            "1043 / 960",
            "915 / 896",
            "1470 / 1400",
            "1420 / 1420",
            "486 / 977",
          ],
          engine: [
            "Бензиновый 1,5TMPI",
            "2WD",
            "Коробка передач с двойным сцеплением мокрого типа (DCT)",
            "Евро 6",
            "4 цилиндра в ряд",
            "16 клапанов",
            "1498",
            "Распределенный впрыск топлива с электронным управлением",
            "Микропроцессорная",
            "Бензин с октановым числом не менее 92",
            "108 / 5500",
            "147 / 5500",
            "210 / (1750 - 4000)",
            "9,5:1",
          ],
          weight: ["1628", "1928"],
          dymanics: ["180", "11,8"],
          fueleconomy: ["57", "10,3", "6,5", "7,8"],
          brakes: ["Дисковые / Дисковые"],
          suspension: [
            "Независимая, типа Макферсон, пружинная, с телескопическими гидравлическими амортизаторами и стабилизатором поперечной устойчивости.",
            "Независимая, многорычажная, пружинная, с телескопическими гидравлическими амортизаторами и стабилизатором поперечной устойчивости.",
          ],
          warmoptions: [true, true, true, true, true, true, true],
          security: [
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
          ],
          exterior: [
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
          ],
          comfort: [
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
          ],
          interior: [
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
          ],
          mult: [
            true,
            false,
            true,
            true,
            false,
            "6",
            false,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
          ],
        },
      },
      {
        img: "https://jetour-atlantm.by/uploads/car-model-compare-landing/bg/7b/bG7BB6MqxO_AUTO_AUTO.webp",
        title: "Luxury +",
        price: "106 900",
        option: {
          dimensions: [
            "4590",
            "1900",
            "1685",
            "948",
            "922",
            "1610 / 1615",
            "19° / 22°",
            "2720",
            "160",
          ],
          capacity: [
            "1043 / 960",
            "915 / 896",
            "1470 / 1400",
            "1420 / 1420",
            "486 / 977",
          ],
          engine: [
            "Бензиновый 1.6TGDI-7DCT",
            "2WD",
            "Коробка передач с двойным сцеплением мокрого типа (DCT)",
            "Евро 6",
            "4 цилиндра в ряд",
            "16 клапанов",
            "1598",
            "Распределенный впрыск топлива с электронным управлением",
            "Микропроцессорная",
            "Бензин с октановым числом не менее 92",
            "140 / 5500",
            "190 / 5500",
            "275 / (2000 - 4000)",
            "9,9:1",
          ],
          weight: ["1655", "1955"],
          dymanics: ["180", "10,5"],
          fueleconomy: ["57", "11,1", "6,8", "8,4"],
          brakes: ["Дисковые / Дисковые"],
          suspension: [
            "Независимая, типа Макферсон, пружинная, с телескопическими гидравлическими амортизаторами и стабилизатором поперечной устойчивости.",
            "Независимая, многорычажная, пружинная, с телескопическими гидравлическими амортизаторами и стабилизатором поперечной устойчивости.",
          ],
          warmoptions: [true, true, true, true, true, true, true],
          security: [
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
          ],
          exterior: [
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
          ],
          comfort: [
            true,
            false,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
          ],
          interior: [
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
          ],
          mult: [
            false,
            true,
            true,
            true,
            true,
            "8",
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
          ],
        },
      },
    ],
  },
  {
    model: "X90PLUS",
    title: "Jetour X90PLUS",
    mainphoto:
      "https://jetour-atlantm.by/uploads/car-model-landing/kf/yi/KFyiDNPk9p_AUTO_AUTO.webp",
    subtitle: "полноразмерный кроссовер SUV-D",
    price: "116 900",
    img: "https://jetour-atlantm.by/uploads/tmp/pw/5m/Pw5MbWwqVw.png",
    body: {
      color: {
        black: [
          "https://jetour-atlantm.by/uploads/car-model-landing/vf/qw/vfQWVRfPaS_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/wn/wf/WNWF3FOeRI_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/ve/qa/vEQAlbPVwa_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/rt/3v/rT3vqcJ6aA_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/4w/iw/4wiW3bWfZb_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/rw/tj/RwTJ9ZMvSV_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/u3/m8/u3M8IqUfNe_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/97/jt/97jTuWJnJg_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/ck/wo/CkWoXO2EIL_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/dk/2q/DK2QBcdFPW_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/yz/wi/YzwinMreLj_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/qt/dm/QtdmYfn0Fq_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/pq/wp/PQwPae7k9n_AUTO_AUTO.webp",
        ],
        blue: [
          "https://jetour-atlantm.by/uploads/car-model-landing/xs/gr/xsGRSuwK6y_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/m2/m9/M2m9I4IddB_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/ur/x5/URX5haVdS4_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/qr/86/qR86XC5evS_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/9c/4c/9C4CFI8jm3_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/kv/my/KVmygjYVw8_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/x7/mj/x7MJeD8gsY_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/mw/lm/MwlMh7h3xD_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/cp/ou/CpOUgYmkVs_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/kl/x0/KLx08qaaqK_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/a0/rn/A0rnSqyBzM_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/yv/oo/yvOoEKz0cj_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/b6/z3/B6z3aKpify_AUTO_AUTO.webp",
        ],
        white: [
          "https://jetour-atlantm.by/uploads/car-model-landing/2l/sn/2lSnWfjDax_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/tu/y8/TUY8yxGBvI_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/vy/cp/vYCPY463s0_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/sl/yd/SLYdlvvjSk_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/hq/gh/HQghkcvQTN_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/yy/2j/YY2j3Rg8mH_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/np/na/nPNaujdPxK_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/6v/td/6vtDUEcblX_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/2f/d4/2Fd4N22nNr_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/uh/cv/UHCVmcrXxK_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/1w/3o/1w3OE7weCk_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/pu/ur/PUurdZFqWA_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/c5/kt/c5KTkn0Gz2_AUTO_AUTO.webp",
        ],
      },
    },
    interior: {
      color: {
        black: [
          "https://jetour-atlantm.by/uploads/car-model-landing/cx/bm/CXBM7IOxfH_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/t5/ew/t5eWeOdBuQ_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/u9/py/U9PyYOcsVv_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/yb/ig/YbIGHumpVc_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/h8/6f/H86fMtwmQG_AUTO_AUTO.webp",
        ],
        red: [
          "https://jetour-atlantm.by/uploads/car-model-landing/di/lo/diLOOztDXd_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/d9/xi/D9xIdr3Gir_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/yf/p3/yFp3m0qi8Z_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/yg/kz/yGKZ2ShiVv_AUTO_AUTO.webp",
          "https://jetour-atlantm.by/uploads/car-model-landing/si/wu/sIWUbcfCWv_AUTO_AUTO.webp",
        ],
      },
    },
    info: [
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/lb/3m/lB3MPBztS1_AUTO_AUTO.webp",
        value: "190 км/ч",
        desc: "макс. скорость",
      },
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/ek/ci/eKci0uZ3fN_AUTO_AUTO.webp",
        value: "57 л",
        desc: "объем бака",
      },
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/8s/xg/8SxGiD4ebE_AUTO_AUTO.webp",
        value: "8 л",
        desc: "комб. расход",
      },
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/s5/mc/S5Mc9sc78e.png",
        value: "4858 мм",
        desc: "длина",
      },
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/n5/gs/n5gs8KM3I9_AUTO_AUTO.webp",
        value: "244 л с",
        desc: "мощность",
      },
      {
        icon: "https://jetour-atlantm.by/uploads/car-model-landing/f7/7t/f77tSxRuUW_AUTO_AUTO.webp",
        value: "5",
        desc: "полноценных мест",
      },
    ],
    about: {
      titlepage: "Большой семейный кроссовер",
      descpage: `Jetour X90PLUS – вместительный кроссовер, созданный для комфортных семейных поездок на дальние расстояния. Он прежде всего ориентирован на аудиторию, у которой увлекательные путешествия на автомобиле – это образ жизни. Просторный X90PLUS от Jetour – яркий пример того, насколько полной и привлекательной может быть гармония между людьми, жизнью и автомобилем.<br/><br/>
  
   
  
      Позвольте себе воплотить мечту о владении автомобилем с непревзойденным  Jetour X90PLUS.`,
      img: "https://jetour-atlantm.by/uploads/car-model-landing/gf/yh/gFyhp8lphK_AUTO_AUTO.webp",
    },
    slider: [
      "https://jetour-atlantm.by/uploads/car-model-landing/pu/ov/PUOvB1p244.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/iz/ch/IZCHVE9ft3_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/hc/qy/HcQYwPLP7R_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/vr/tl/vrTLYBUQuF.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/la/4d/lA4d3IQXpk.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/s3/fu/S3FUsAOQPc_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/7k/fm/7kfmIGbB5O.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/lb/9v/LB9VcqdUYI_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/od/r8/odr86LJdxs.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/fk/k3/FKK32cvee0_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/oh/r5/oHR53IQ8KE.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/h6/rp/H6RpylwTqK_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/4z/y5/4zy5isREVK_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/hz/lk/HzlkmGw4OU_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/fu/ts/fuTs3FUYUz_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/qw/do/QwDOehG5ec_AUTO_AUTO.webp",
      "https://jetour-atlantm.by/uploads/car-model-landing/8h/ks/8HksyAK8gM_AUTO_AUTO.webp",
    ],
    hang: [
      {
        title: "Благородный дизайн",
        desc: `Jetour X90PLUS - это автомобиль, который притягивает взгляды и вызывает восхищение. Он сочетает в себе элегантность, современность и функциональность, делая его идеальным выбором для тех, кто ценит стиль и инновации.<br/><br/> 

 

        Внешность Jetour X90PLUS просто потрясает своим великолепием и уникальностью. Этот автомобиль сочетает в себе элегантность, смелость и динамичность, привлекая восхищенные взгляды везде, где он появляется.<br/><br/>
        
         
        
        Стиль и внешний вид Jetour X90PLUS - это не просто внешние качества, но и отражение его характера и индивидуальности. Он идеально подходит для тех, кто хочет выделиться, проявить свою смелость и стиль. Jetour X90PLUS - это автомобиль, который вызывает восхищение и станет вашим надежным спутником в путешествиях и повседневной жизни.`,
        img: "https://jetour-atlantm.by/uploads/car-model-landing/og/nb/OGnb3DdUJB_AUTO_AUTO.webp",
        options: [
          {
            title: "20-дюймовые легкосплавные диски",
            desc: "20-дюймовые легкосплавные диски оригинального дизайна придают кроссоверу брутальный вид, добавляя характера всему внешнему облику автомобиля. Подчеркнутые пластиковыми вставками колесные арки делают внешность Jetour X90PLUS еще более решительной.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/vb/us/vBuSh3vO4C_AUTO_AUTO.webp",
          },
          {
            title: "Непревзойденный дизайн задней части",
            desc: "А задняя часть автомобиля вызывает настоящий восторг. Хвостовые фонари с уникальным дизайном и интегрированный спойлер придают X90PLUS Jetour завершенность и аэродинамичность. Он просто манит к себе взгляды, заставляя окружающих поворачиваться на улице. Представляем вам эволюционные фары Jetour X90PLUS. Они не просто освещают дорогу, а создают настоящую атмосферу элегантности и стиля. Современный дизайн и инновационные технологии задних фар Jetour X90PLUS привлекут внимание всех, кто окажется на вашем пути. С их помощью вы сможете выделиться на дороге и подчеркнуть свою индивидуальность. Фонари включают  236 LED элементов",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/g2/jm/g2jmvlNMhP_AUTO_AUTO.webp",
          },
          {
            title: "Грациозная решетка радиатора",
            desc: "Дизайн передней части Jetour X90PLUS просто поражает воображение. Он воплощает современные тренды и элегантность в каждой детали. Уникальный стиль и изящные линии придают автомобилю выразительность и привлекательность. Отличительной особенностью является грациозная решетка радиатора, которая добавляет автомобилю благородства и утонченности. Она прекрасно сочетается с динамичными фарами, создавая единый гармоничный образ. Каждая деталь передней части Jetour X90PLUS продумана до мелочей. От широких воздухозаборников, обеспечивающих оптимальную вентиляцию двигателя, до элегантных хромированных акцентов, которые подчеркивают премиальность и статус автомобиля. Но дизайн Jetour X90PLUS - это не только красота, но и функциональность. Он оптимизирован для улучшения аэродинамики и снижения сопротивления воздуха, что в свою очередь повышает эффективность и экономичность автомобиля.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/pg/ge/pGGEuBD5I3_AUTO_AUTO.webp",
          },
          {
            title: "Изящные линии и элегантные пропорции",
            desc: "Сбоку X90PLUS вы обнаружите изящные линии и элегантные пропорции, которые создают гармоничный образ автомобиля. Профиль X90PLUS Jetour выглядит стильно и современно, подчеркивая его спортивные характеристики и эффективность.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/c7/aw/C7aW5uvHEt_AUTO_AUTO.webp",
          },
        ],
      },
      {
        title: "X90PLUS - реально большой",
        desc: `В части габаритных размеров вместительный Jetour X90PLUS – один из наиболее крупных переднеприводных кроссоверов D-класса, в котором предлагается и обилие пространства для пассажиров, и масса места для багажа. Каждый сантиметр X90PLUS заботится о том, чтобы любое путешествие доставляло его экипажу исключительно положительные эмоции.`,
        img: "https://jetour-atlantm.by/uploads/car-model-landing/wu/e0/wue0C79dO5_AUTO_AUTO.webp",
        options: [
          {
            title: "Колесная база  2850 мм",
            desc: "Благодаря колесной базе в 2850 мм водителю и пассажирам Jetour X90PLUS все условия для комфортабельных поездок на любые расстояния.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/6i/sz/6ISZX52PXj_AUTO_AUTO.webp",
          },
          {
            title: "Дорожный просвет 210 мм",
            desc: "Благодаря минимальному дорожному просвету в 210 мм Jetour X90PLUS с легкостью может покинуть пределы асфальта, без опасений повредить что-либо под днищем автомобиля. Это делает спектр его возможностей еще шире.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/3t/p5/3TP5a8NqEu_AUTO_AUTO.webp",
          },
          {
            title:
              "Ширина передней колеи кроссовера составляет 1600 мм, задней – 1605 мм.",
            desc: "Ширина передней колеи кроссовера составляет 1600 мм, задней – 1605 мм. В сочетании с колесной базой в 2850 мм это способствует высокой устойчивости автомобиля и обеспечивает ему оптимальную управляемость на любых типах дорожных покрытий.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/lm/sc/LMSc8rJTuu_AUTO_AUTO.webp",
          },
        ],
      },
      {
        title: "Cовершенное сочетание комфорта",
        desc: `Интерьер Jetour X90PLUS - это настоящий шедевр дизайна и комфорта. Каждая деталь продумана с учетом лучших традиций автомобильной индустрии, чтобы предложить вам непревзойденное впечатление от вождения.<br/><br/>

 

        Салон вместительного семейного Jetour X90PLUS – это всегда обилие пространства, отличная эргономика и высокий уровень комфорта для водителя и пассажиров.<br/><br/>
        
         
        
        Приятные внешне отделочные материалы встречают водителя и пассажиров на любом из мест просторного кроссовера. Передняя панель автомобиля радует взор не только высококачественной комбинированной отделкой из экокожи и пластиковых накладок, очень натурально имитирующих природную древесину, а и тремя информативными цветными экранами, два из которых сенсорные.`,
        img: "https://jetour-atlantm.by/uploads/car-model-landing/wr/08/wR085jh1E2_AUTO_AUTO.webp",
        options: [
          {
            title: "Обилие регулировок сидений",
            desc: "Обилие регулировок сидений кроссовера, без труда позволяет подобрать для себя оптимальный вариант посадки на любом из мест Jetour X90PLUS.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/md/nx/MdnxfTcBHX.webp",
          },
          {
            title: "Функциональная и элегантная приборная панель",
            desc: "Приборная панель и центральная консоль выполнены в современном стиле, сочетающем в себе функциональность и элегантность. Интуитивно понятные элементы управления и инновационные технологии позволяют вам контролировать различные функции автомобиля с легкостью и удовольствием.  Экран  диагональю 12,3”, объединенный в один блок со щитком приборов аналогичного размера, позволяет управлять медиасистемой, и общими настройками автомобиля. Второй, с диагональю  9,7”, предлагает массу возможностей для установки максимально комфортабельных настроек двухзонной климатической установки, воздуховоды которой есть не только впереди и сзади, а и на потолке автомобиля. Вербально в Jetour X90PLUS можно также управлять стеклами дверей, включением радио или музыки, работой климат-контроля и навигации.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/kc/9m/Kc9MSCRuC0_AUTO_AUTO.webp",
          },
          {
            title:
              "Высококачественная отделка и использование премиальных материалов",
            desc: "Сразу бросается в глаза высококачественная отделка и использование премиальных материалов. Кожаные сиденья и мягкие поверхности создают атмосферу роскоши и комфорта, позволяя вам наслаждаться каждой поездкой. Они также обеспечивают отличную поддержку и эргономику, что особенно важно во время длительных поездок. Атмосферу уюта дополняют эргономичные сиденья.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/8j/sj/8jSjT6EIaL.webp",
          },
          {
            title: "Панорамный люк на крыше с площадью  1,1 кв. м.",
            desc: "Панорамный люк на крыше с площадью, 1,1 кв. м., в Jetour X90PLUS при необходимости можно закрыть электроуправляемой шторкой, которая активизируется как рычажком, расположенным рядом с салонным зеркалом заднего вида, так и обычной голосовой командой «Закрой шторку люка». И это далеко не единственное, действие, которое автомобиль позволяет начать, просто произнеся голосовую команду.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/xv/cj/xVcJdma8NP_AUTO_AUTO.webp",
          },
          {
            title: "Большой багажник",
            desc: "Объем багажника составляет 486 литров, а при сложенных сиденьях 2 ряда – 1052 литров.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/gf/ja/gFJAGXW3bw.webp",
          },
          {
            title: "Просторный и функциональный салон",
            desc: "Комфорт пассажиров также получил особое внимание. Просторный салон и щедрые пространства для ног обеспечивают максимальный комфорт для всех пассажиров. Кроме того, наличие различных отсеков для хранения позволит вам организовать свои личные вещи и сохранить салон в порядке. Охлаждаемый подлокотник, вместительный перчаточный ящик и обилие мест для хранения разного рода мелочей, часто необходимых в путешествии – вещи само-собой разумеющиеся. Сюда же можно добавить USB-порты для зарядки гаджетов и беспроводную зарядку для телефона на центральной консоли между водителем и передним пассажиром.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/do/wa/dOwaHq85bl_AUTO_AUTO.webp",
          },
        ],
      },
      {
        title: "Впечатляющий набор передовых технологий",
        desc: `Jetour X90PLUS обладает впечатляющим набором передовых технологий, которые сделают вашу поездку еще более комфортной и безопасной. Одной из ключевых технологий является система интеллектуального управления автомобилем, которая позволяет вам контролировать различные функции автомобиля с помощью голосовых команд или жестов. Это не только удобно, но и повышает безопасность на дороге, позволяя вам сосредоточиться на вождении.`,
        img: "https://jetour-atlantm.by/uploads/car-model-landing/vp/mh/VPmhSnYldx_AUTO_AUTO.webp",
        options: [
          {
            title: "Система очистки воздуха",
            desc: "Система очистки воздуха оснащена воздушным фильтром стандарта CN95, обеспечивающим фильтрацию воздуха на 95%, и генератором отрицательных ионов, что позволяет наслаждаться чистым воздухом в салоне",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/td/8y/tD8ycG38fx_AUTO_AUTO.webp",
          },
          {
            title: "Пакет зимних опции",
            desc: "Зимний пакет, теперь также доступный в Jetour X90 PLUS, включает в себя дополнительные опции для обеспечения комфорта и безопасности в холодное время года.  Обогрев ветрового стекла (Heated Windshield) помогает быстро размораживать и очищать стекло ото льда, снега и инея после длительной стоянки. Он также предотвращает образование запотевания на стеклах, обеспечивая водителю хороший обзор. Обогрев руля (Heated Steering Wheel) повышает комфорт от управления Jetour X90PLUS при низких температурах. При включении этой функции обод рулевого колеса нагревается, что помогает избежать ощущения холода и сохранить удобство управления автомобилем. Обогрев сидений (Heated Seats) обеспечивает комфорт и уют для водителя и пассажиров, быстро согревая сиденья в холодные дни. Обогрев форсунок стеклоомывателей (Heated Washer Nozzles) предотвращает их замерзание и обледенение при температурах ниже нуля.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/rc/jy/rCJYbQRIWE.png",
          },
          {
            title: "Беспроводная зарядка для мобильного телефона",
            desc: "Беспроводная зарядка для устройств на центральном тоннеле, практичные подстаканники и USB-порты для зарядки электронных гаджетов обеспечивают удобство и свободу в использовании современных технологий в пути.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/q7/fw/Q7fwgoGKlp_AUTO_AUTO.webp",
          },
          {
            title: "Премиальная аудиосистема",
            desc: "Премиальная аудиосистема Sony с 8 динамиками создает обеспечивает качественное звучание воспроизводимой мультимедийной системой музыки.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/fv/mx/fvMXomuHaj_AUTO_AUTO.webp",
          },
          {
            title: "Превосходная звукоизоляция",
            desc: "Интерьер Jetour X90PLUS также обладает превосходной звукоизоляцией, которая позволяет вам наслаждаться тишиной и спокойствием внутри салона. Это создает идеальную атмосферу для отдыха и расслабления, особенно в долгих поездках.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/uh/j9/uhj91sr5L6_AUTO_AUTO.webp",
          },
          {
            title: "Продвинутая мультимедиа и система навигации",
            desc: "Также стоит отметить систему мультимедиа и связи, которая позволяет вам наслаждаться вашей любимой музыкой и поддерживать связь с внешним миром. Вы сможете подключить ваш смартфон или другие устройства через Bluetooth или USB, а также использовать голосовое управление для удобства и безопасности.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/cz/bq/cZbQA7s2y7_AUTO_AUTO.webp",
          },
        ],
      },
      {
        title: "Безусловная безопасность",
        desc: `Jetour X90PLUS - верный спутник на дороге, который сосредоточен на вашей безопасности.<br/><br/>
        
        Снабженный передовыми технологиями и инновационными функциями этот автомобиль обеспечивает защиту вас и ваших пассажиров на каждом этапе поездки.<br/><br/>

        Оснащенный фронтальными и боковыми подушками безопасности, боковыми шторками безопасности, системой крепления детских кресел ISOFIX, автоматической блокировкой дверей в движении, датчиком столкновения и антиблокировочной системой тормозов Jetour X90PLUS предлагает всестороннюю защиту в случае возможных аварийных ситуаций.`,
        img: "https://jetour-atlantm.by/uploads/car-model-landing/hx/9k/hx9kbS1DA8_AUTO_AUTO.webp",
        options: [
          {
            title: "Антиблокировочная система тормозов",
            desc: "Чтобы предотвратить блокировку колес и повысить управляемость, все Jetour X90PLUS  по умолчанию оснащены антиблокировочной системой тормозов, которая позволяет безопасно и контролируемо снижать скорость и делать необходимые маневры на дороге.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/2e/ai/2eai7bKq5O_AUTO_AUTO.webp",
          },
          {
            title: "Инновационные подушки безопасности",
            desc: "Фронтальные подушки безопасности для водителя и переднего пассажира гарантируют им надежную защиту при фронтальном столкновении. Боковые подушки безопасности передних сидений дополнительно обеспечивают защиту в случае бокового столкновения либо удара в препятствие под углом, снижая риск получения серьезных повреждений. Jetour X90PLUS  также оснащен боковыми шторками безопасности, задача которых предотвратить травмы у водителя и пассажиров при боковом ударе, создавая дополнительный барьер между людьми и потенциальной опасностью.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/zg/q1/ZGQ1JaFYl0_AUTO_AUTO.webp",
          },
          {
            title: "Системы крепления детских кресел",
            desc: "Заботясь о юных пассажирах, для перевозки которых используются детские сиденья, Jetour X90PLUS  предлагает систему крепления детских кресел ISOFIX. С этой системой установка детского кресла становится легкой и надежной, при этом обеспечивается высокий уровень безопасности и комфорта для самых маленьких пассажиров кроссовера.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/iv/ik/IViKleoYT8.webp",
          },
          {
            title: "Высокопрочная сталь кузова",
            desc: "Доля высокопрочной стали в каркасе кузова составляет 70%. Предел прочности используемой стали достигает 1500 МПа. 54% панелей кузова имеет двухстороннюю оцинковку.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/kr/2e/KR2EUBVJqO.webp",
          },
          {
            title: "Автоматическая блокировка дверей",
            desc: "Автоматическая блокировка дверей в движении обеспечивает дополнительную безопасность, предотвращая случайное открытие дверей в процессе езды. Это гарантирует, что все двери останутся надежно закрытыми до тех пор, пока автомобиль не остановится полностью. В случае аварии в Jetour X90PLUS  срабатывает датчик столкновения, который мгновенно разблокирует двери, обеспечивая быстрый и безопасный выход для вас и ваших пассажиров.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/rq/rh/rqRhAbtyzo_AUTO_AUTO.webp",
          },
        ],
      },
      {
        title: "Интеллектуальные ассистенты",
        desc: `Jetour X90PLUS  обладает обширным набором систем помощи водителю, предназначенных для обеспечения высокого уровня безопасности и комфорта в процессе управления кроссовером.<br/><br/>
        
        Используя новейшие технологии, новый Jetour X90PLUS  будет держать Вас в курсе ситуации на дороге и заранее сообщать о возможных препятствиях. Интеллектуальные системы безопасности и помощи водителю  вмешаются именно в тот момент, когда это поможет предотвратить столкновение и обеспечить безопасность Вам и другим участникам движения.`,
        img: "https://jetour-atlantm.by/uploads/car-model-landing/sa/to/saToA8edyO.webp",
        options: [
          {
            title: "Система контроля слепых зон",
            desc: "Система контроля слепых зон мониторит области, находящиеся вне прямого поля зрения водителя, и предупреждает о наличии транспортных средств в слепых зонах. В ходе своей работы она использует радары или камеры, расположенные на заднем бампере, и предупреждает водителя с помощью звуковых или визуальных сигналов.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/hl/va/hLva4C2KEg.webp",
          },
          {
            title: "Бесключевой запуск двигателя",
            desc: "Бесключевой запуск двигателя (Keyless Engine Start) позволяет водителю запускать двигатель автомобиля без использования ключа. Водителю достаточно нажать кнопку запуска, просто находясь с ключом в автомобиле, что делает запуск двигателя куда более комфортным и удобным. В дополнение к этому в X90PLUS предусмотрена и возможность дистанционного запуска силового агрегата кроссовера.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/kd/av/kDaVhODI2g_AUTO_AUTO.webp",
          },
          {
            title: "360-Degree Camera System",
            desc: "Камеры кругового обзора (360-Degree Camera System), расположенные вокруг автомобиля, предоставляют водителю полный обзор пространства, окружающего кроссовер. Отображая полученные изображения на мультимедийном экране, они помогают водителю маневрировать в ограниченном пространстве и парковаться, избегая столкновений с окружающими препятствиями.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/qz/vx/qZVxGZc2Xz.webp",
          },
          {
            title: "Система предупреждения о столкновении",
            desc: "Система предупреждения о столкновении (Forward Collision Warning) мониторит дорожную обстановку перед автомобилем. В случае обнаружения препятствия или возможности столкновения упомянутая система также предупреждает водителя звуковыми и визуальными сигналами, чтобы помочь избежать аварий.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/k6/mu/K6muLob0ia.webp",
          },
          {
            title: "Система контроля температуры и давления в шинах",
            desc: "Система контроля температуры и давления в шинах (Tire Pressure Monitoring System) мониторит давление воздуха и температуру в шинах автомобиля. Если давление становится ниже рекомендуемого уровня или возникают аномальные значения температуры, система предупреждает водителя о необходимости проверки и подкачки шин.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/r1/p4/r1p45cK6FW_AUTO_AUTO.webp",
          },
          {
            title: "Передовые системы торможения",
            desc: "Системы помощи при подъеме на холм  и спуска со склона  помогают водителю управлять автомобилем при движении по крутым подъемам и спускам. Они могут автоматически регулировать тормоза и мощность двигателя, чтобы предотвратить скатывание назад или ускорение вниз. Электронная система экстренного торможения в случае необходимости экстренного торможения и недостаточного при этом усилия на педали тормоза самостоятельно повышает давление в тормозной магистрали, делая это намного и эффективнее человека, управляющего автомобилем. Электронная система стабилизации  контролирует курсовую устойчивость автомобиля путем регулирования мощности и тормозных усилий на отдельных колесах. Она помогает предотвратить заносы автомобиля при резких маневрах или на скользком покрытии дороги. Противобуксовочная система  предотвращает проскальзывание ведущих колес при разгоне на скользкой поверхности или на поверхности с разными коэффициентами сцепления колес с дорогой. Регулируя величину крутящего момента, она обеспечивает его оптимальное распределение между ведущими колесами автомобиля.",
            img: "https://jetour-atlantm.by/uploads/car-model-landing/zz/51/Zz51qraWCS_AUTO_AUTO.webp",
          },
        ],
      },
    ],
    delivery: {
      img: "https://jetour-atlantm.by/uploads/car-model-landing/qj/bm/QJBMRrL54S.png",
      carsdelivery: [
        {
          title: "Галактический черный",
          img: "https://jetour-atlantm.by/uploads/car-model-landing/3a/wd/3AwDOI7VFE_AUTO_AUTO.webp",
          complect: [
            "X90PLUS | Компл.: Luxury | Двигатель: 1.6T+7DCT | Кузов: Black | Интерьер: Red-brown",
            "(БРОНЬ) X90PLUS | Компл.: Luxury + | Двигатель: 2.0T+7DCT | Кузов: Black | Интерьер: Red-brown",
            "X90PLUS | Компл.: Luxury + | Двигатель: 2.0T+7DCT | Кузов: Black | Интерьер: Black",
          ],
        },
        {
          title: "Океанический синий",
          img: "https://jetour-atlantm.by/uploads/car-model-landing/ks/av/KsAvyacTpo_AUTO_AUTO.webp",
          complect: [
            "X90PLUS | Компл.: Luxury | Двигатель: 1.6T+7DCT | Кузов: Blue | Интерьер: Black",
            "X90PLUS | Компл.: Luxury + | Двигатель: 2.0T+7DCT | Кузов: Blue | Интерьер: Black",
            "(БРОНЬ) X90PLUS | Компл.: Luxury + | Двигатель: 2.0T+7DCT | Кузов: Blue | Интерьер: Red-brown",
          ],
        },
        {
          title: "Призрачный серый",
          img: "https://jetour-atlantm.by/uploads/car-model-landing/hm/n2/hMn2PHZTGn_AUTO_AUTO.webp",
          complect: [
            "(БРОНЬ) X90 PLUS | Компл.: Luxury | Двигатель: 1.6T+7DCT | Кузов: Gray | Интерьер: Black",
            "X90 PLUS | Компл.: Luxury + | Двигатель: 2.0T+7DCT | Кузов: Gray | Интерьер: Black",
            "X90 PLUS | Компл.: Luxury + | Двигатель: 2.0T+7DCT | Кузов: Gray | Интерьер: Red-brown",
          ],
        },
        {
          title: "Арктический белый",
          img: "https://jetour-atlantm.by/uploads/car-model-landing/7u/q0/7Uq0kIRddH_AUTO_AUTO.webp",
          complect: [
            "(БРОНЬ) X90 PLUS | Компл.: Luxury + | Двигатель: 2.0T+7DCT | Кузов: White | Интерьер: Black",
            "X90 PLUS | Компл.: Luxury + | Двигатель: 2.0T+7DCT | Кузов: White | Интерьер: Red-brown",
            "X90 PLUS | Компл.: Luxury | Двигатель: 1.6T+7DCT | Кузов: White | Интерьер: Black",
          ],
        },
      ],
    },
    photoForm:
      "https://jetour-atlantm.by/uploads/car-model-landing/5n/ps/5NpS0E6tC4_AUTO_AUTO.webp",
  },
];
